[build]
builder = "NIXPACKS"

[build.nixpacks]
languages = ["python", "node"]

[build.plan]
providers = ["python", "node"]

[build.steps]
steps = [
  "npm install",
  "npm run build",
  "pip install -r requirements.txt"
]

[start]
command = "gunicorn --workers 4 --bind 0.0.0.0:$PORT wsgi:app"
